# Generated by Django 4.2.5 on 2024-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_watched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
