# Generated by Django 4.2.5 on 2024-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_history_watched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='showId',
            field=models.IntegerField(),
        ),
    ]
